import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Avinash | Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className='min-h-[calc(100vh-14rem)]'>
          {children}
        </div>
        <div className='w-full bg-black left-0 bottom-0'>
          <Footer />
        </div>

      </body>
    </html>
  )
}
